### PR TITLE
Fix invalid reference to item field and remove unused variables

### PR DESCRIPTION
**Pull request by Ingramz**

### CODE REVIEW

**Comment by 50Wliu** [comment]
> No description provided.

What does this fix?  Are there any open issues pertaining to this? etc.

**Comment by Ingramz** [comment]
It's a mistake or unintended feature that coffeescript allowed in older versions. Newer versions of coffeescript transpile the `item` parameter as `item1` to avoid naming conflict with the line that was changed. If you use an older version of coffeescript, it fixes nothing, in newer versions the code would fail.

**Comment by Ingramz** [comment]
Also removed some unused variables that were found with coffeescope. I verified that the "invalid" reference was the only one.

**Comment by 50Wliu** [comment]
Thanks!

**Pull request merged**
