### PR TITLE
Fix positioning of placeholder with multiline tabs

### PR DESCRIPTION
**Pull request by forivall**
This fixes positioning of the placeholder in themes with multiline tabs (where I just updated mine to do this: https://atom.io/packages/adwaita-pro-ui)

### CODE REVIEW

**Comment by forivall** [comment]
Also provided by https://atom.io/packages/multirow-tabs

**Comment by lee-dohm** [comment]
I've added this to the queue for review. Would you mind updating it to resolve the conflicts?

**Comment by forivall** [comment]
Done! Twas a bit of work, since y'all removed your use of jquery :fearful:

**Comment by 50Wliu** [comment]
Looks like you have a failing spec related to your change @forivall.
https://travis-ci.org/atom/tabs/builds/118844936#L182

**Comment by forivall** [comment]
Sorry for the long delay. @50Wliu @lee-dohm updated.

**Comment by 50Wliu** [comment]
Can you show a before/after image @forivall?  I'm not sure I understand what the "placeholder" you're referring to is.

**Comment by forivall** [comment]
It's the blue thing.
Before: 
atom-tabs-multiline-fix-before

After: 
atom-tabs-multiline-fix-after

**Comment by simurai** [comment]
A [change in how flexbox works](https://developers.google.com/web/updates/2016/06/absolute-positioned-children) forced us to make the `.placeholder` element be relatively positioned (PR https://github.com/atom/tabs/pull/384). And I think as a side effect, it also fixed this issue.

tabs

Should already be in the [new Beta](https://atom.io/beta) (`1.12`) if somebody wants to try.

**Comment by Ben3eeE** [comment]
Closing this one since it is already fixed by https://github.com/atom/tabs/pull/384.

**Pull request closed without merging**
