### PR TITLE
Make tab opening position at end option

### PR DESCRIPTION
**Pull request by Xcodo**
Some people (me!) like new tabs to sit at the end of the tab list, not next to the current tab.

This PR adds an option "Always open new tab at end" to the tabs package settings.

This was briefly discussed at https://discuss.atom.io/t/newly-opened-tab-order/20822

### CODE REVIEW

**Comment by mnquintana** [comment]
Would you mind adding tests for this?

**Comment by Xcodo** [comment]
Sorry that I seemed to skip over the bit about tests when reading the contributing guide.

Anyway, I've gone away and learnt what Jasmine is and added to the specs.

My tests are passing and the Travis CI build has succeeded, but my local suite fails. I'm not sure why:
atomspecfail

**Comment by Xcodo** [comment]
@mnquintana This has been sitting open for a while. Will it get actioned? If it will I'll keep putting effort into resolving the conflicts with master every once in a while, but it's a bit of a pain!

**Comment by simurai** [comment]
> Some people

Me too! Sometimes I like to keep a few tabs sorted. Having new tabs open in between throws off the order.

**Comment by docnoe** [comment]
Looking forward to this, please merge!

**Comment by 50Wliu** [comment]
I believe this has already been added with the `Add New Tabs at End` option.  Really sorry for missing this PR @Xcodo :disappointed:.

**Pull request closed without merging**
